chore(git): forbit protected branch push

diff --git a/scripts/githooks/pre-commit b/scripts/githooks/pre-commit
--- a/scripts/githooks/pre-commit
+++ b/scripts/githooks/pre-commit
@@ -25,4 +25,14 @@ then
     exit 1
 fi
 
+# avoid push to protected branch directly
+protected_branch="$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')"
+branch="$(git rev-parse --abbrev-ref HEAD)"
+
+# a branch name where you want to prevent git push. In this case, it's "master"
+if [ "$branch" = "$protected_branch" ]; then
+  echo "You can't commit directly to '"${branch}"' branch" # webstorm or intellij will show this as popup
+  exit 1 # if you remove this line then it won't block push but send message to group and on command line
+fi
+
 exit 0
